# sensor drivers
obj-$(CONFIG_INV_ACCEL)					+= accel/
obj-$(CONFIG_INV_COMPASS)				+= compass/
obj-$(CONFIG_INV_GYRO)					+= mpu/

obj-$(CONFIG_INV_LIGHT)					+= lsensor/
#obj-$(CONFIG_INV_PROXIMITY)				+= psensor/

